'use client';

import { useEffect, useState } from 'react';
import { getSupabaseClient } from '@/lib/supabase/client';

type Distribution = { label: string; count: number };
type Analytics = { growth: Array<{ date: string; count: number }>; statuses: Record<string, number>; platforms: Distribution[]; primaryPlatforms: Distribution[]; niches: Distribution[]; cities: Distribution[]; creatorTypes: Distribution[]; completion: { average: number; completed: number; incomplete: number } };
const count = (value: unknown) => Number(value || 0).toLocaleString('en-US');

function DistributionList({ title, items }: { title: string; items: Distribution[] }) {
  const max = Math.max(...items.map((item) => Number(item.count)), 1);
  return <section className="rounded-2xl border border-[#e8e7eb] bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold tracking-[-0.04em]">{title}</h2>{items.length ? <div className="mt-5 space-y-3">{items.map((item) => <div key={item.label}><div className="flex justify-between gap-3 text-sm"><span className="truncate">{item.label}</span><strong>{count(item.count)}</strong></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#efedf3]"><div className="h-full rounded-full bg-[#8c6ce8]" style={{ width: `${Math.max(5, Number(item.count) / max * 100)}%` }}/></div></div>)}</div> : <p className="mt-5 rounded-xl bg-[#faf9fc] p-4 text-sm text-[#697080]">There is not enough data yet.</p>}</section>;
}

export default function AdminAnalyticsPage() {
  const [data, setData] = useState<Analytics | null>(null); const [sectionCompletion, setSectionCompletion] = useState<Distribution[]>([]); const [error, setError] = useState(false); const [reload, setReload] = useState(0);
  useEffect(() => { let active = true; const supabase = getSupabaseClient(); if (!supabase) { void Promise.resolve().then(() => { if (active) setError(true); }); return; } void Promise.all([supabase.rpc('admin_analytics'), supabase.rpc('admin_completion_by_section')]).then(([analyticsResult, sectionResult]) => { if (!active) return; if (analyticsResult.error || !analyticsResult.data || sectionResult.error || !sectionResult.data) setError(true); else { setData(analyticsResult.data as Analytics); setSectionCompletion(Object.entries(sectionResult.data as Record<string, number>).map(([label, count]) => ({ label: label.replaceAll('-', ' '), count }))); setError(false); } }); return () => { active = false; }; }, [reload]);
  if (error) return <section className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-semibold">Analytics</h1><p className="mt-6 text-sm text-[#9a3f4a]">We could not load analytics.</p><button type="button" onClick={() => { setError(false); setReload((value) => value + 1); }} className="mt-4 rounded-lg bg-[#151518] px-4 py-2 text-sm text-white">Retry</button></section>;
  if (!data) return <section className="mx-auto max-w-6xl px-5 py-10"><div className="h-72 animate-pulse rounded-2xl border border-[#e8e7eb] bg-white" /></section>;
  const statusCards = [['Pending Review', data.statuses.pending], ['Approved', data.statuses.active], ['Rejected', data.statuses.rejected]];
  return <section className="mx-auto w-full max-w-6xl px-5 py-9 sm:px-8 sm:py-12 lg:px-10 lg:py-14"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#7C3AED]">Operational analytics</p><h1 className="mt-3 text-[2.15rem] font-semibold tracking-[-0.06em]">Creator Analytics</h1><p className="mt-3 text-sm text-[#626a7a]">Live operational data from the creator database.</p><div className="mt-8 grid gap-4 sm:grid-cols-3">{statusCards.map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-[#e8e7eb] bg-white p-5"><p className="text-sm text-[#697080]">{label}</p><p className="mt-2 text-3xl font-semibold">{count(value)}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-[#e8e7eb] bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold">Profile completion</h2><p className="mt-5 text-4xl font-semibold tracking-[-0.06em]">{count(data.completion.average)}%</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p className="rounded-xl bg-[#f7f5fb] p-3">Completed<strong className="mt-1 block text-xl">{count(data.completion.completed)}</strong></p><p className="rounded-xl bg-[#f7f5fb] p-3">Incomplete<strong className="mt-1 block text-xl">{count(data.completion.incomplete)}</strong></p></div></section><DistributionList title="Completion by section" items={sectionCompletion}/><DistributionList title="Primary platform distribution" items={data.primaryPlatforms}/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><DistributionList title="Platform adoption" items={data.platforms}/><DistributionList title="Top primary niches" items={data.niches}/><DistributionList title="Top creator cities" items={data.cities}/><DistributionList title="Creator types" items={data.creatorTypes}/></div>{data.growth.length ? <DistributionList title="Creator growth by day" items={data.growth.slice(-14).map((row) => ({ label: row.date, count: row.count }))}/> : null}</section>;
}
